"""
Django settings for CRM project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '@d+t=4=)f3vj3n1yc6evrkrfb!r=59@p6$sm=y_u=tk5$_ya3w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Allowed host
ALLOWED_HOSTS = ['*']

# Application definition
INSTALLED_APPS = [
    'rest_framework',
    'corsheaders',
    'django_crontab',
    'rm_handle_data.apps.common',
    'rm_handle_data.apps.news',
]

CRONJOBS = [
    ('0 0 * * *', 'rm_handle_data.apps.news.service.get_news_daily', ),
]

# Middle ware
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
]

# Root url
ROOT_URLCONF = 'rm_handle_data.urls'

# WSGI
WSGI_APPLICATION = 'rm_handle_data.wsgi.application'

# Database
DATABASES = {
    # Server
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'coin_all',
        'USER': 'ai',
        'PASSWORD': 'N8/8|2b6xE69',
        'HOST': '35.77.100.41',
        'PORT': '3306',
        'charset': 'utf8mb4',
        'OPTIONS': {'charset': 'utf8mb4'},
    }
}

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'Asia/Bangkok'
USE_I18N = True
USE_L10N = True
USE_TZ = False

# Allow cors
CORS_ORIGIN_ALLOW_ALL = True
